import { StyleSheet } from 'react-native';

import { colors } from './constants/theme';

export const styles = StyleSheet.create({
  loading: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  app: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  screen: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  topBar: {
    alignItems: 'center',
    backgroundColor: 'rgba(253,249,242,0.88)',
    flexDirection: 'row',
    justifyContent: 'space-between',
    left: 0,
    paddingHorizontal: 16,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 10,
  },
  topIcon: {
    alignItems: 'center',
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  topTitle: {
    color: colors.primary,
    fontFamily: 'SourceSerif4_700Bold',
    fontSize: 22,
    lineHeight: 30,
  },
  sessionTitle: {
    color: 'rgba(60,74,67,0.7)',
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 12,
    letterSpacing: 1.2,
    lineHeight: 16,
    textTransform: 'uppercase',
  },
  recordTopTitle: {
    fontFamily: 'SourceSerif4_400Regular',
  },
  homeScroll: {
    paddingHorizontal: 16,
    paddingTop: 96,
  },
  greeting: {
    alignItems: 'center',
    marginBottom: 52,
  },
  homeHeadline: {
    color: colors.onSurface,
    fontFamily: 'SourceSerif4_400Regular',
    fontSize: 25,
    lineHeight: 32,
    textAlign: 'center',
  },
  homeQuote: {
    color: 'rgba(67,72,64,0.68)',
    fontFamily: 'SourceSerif4_400Regular_Italic',
    fontSize: 17,
    lineHeight: 27,
    marginTop: 8,
    textAlign: 'center',
  },
  statusSection: {
    alignItems: 'center',
    marginBottom: 44,
    position: 'relative',
  },
  statusAura: {
    backgroundColor: 'rgba(236,232,225,0.28)',
    borderRadius: 145,
    height: 290,
    position: 'absolute',
    top: 0,
    width: 290,
  },
  statusCircle: {
    alignItems: 'center',
    backgroundColor: 'rgba(253,249,242,0.42)',
    borderColor: 'rgba(195,200,189,0.36)',
    borderRadius: 102,
    borderWidth: 1,
    height: 204,
    justifyContent: 'center',
    width: 204,
  },
  statusLabel: {
    color: colors.outline,
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 12,
    letterSpacing: 1.2,
    lineHeight: 16,
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  statusText: {
    color: colors.primary,
    fontFamily: 'SourceSerif4_700Bold',
    fontSize: 25,
    lineHeight: 32,
  },
  todayMinutes: {
    color: colors.onSurface,
    fontFamily: 'SourceSerif4_300Light',
    fontSize: 42,
    lineHeight: 50,
    marginTop: 24,
    textAlign: 'center',
  },
  todayUnit: {
    color: colors.variant,
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 12,
    letterSpacing: 1.2,
    lineHeight: 16,
  },
  capsLabel: {
    color: colors.outline,
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 12,
    letterSpacing: 1.2,
    lineHeight: 16,
    textTransform: 'uppercase',
  },
  ctaCard: {
    alignItems: 'center',
    backgroundColor: colors.surfaceCard,
    borderColor: 'rgba(255,255,255,0.62)',
    borderRadius: 24,
    borderWidth: 1,
    minHeight: 184,
    justifyContent: 'center',
    marginBottom: 12,
    paddingVertical: 34,
    boxShadow: '0 12px 40px rgba(0,0,0,0.10)',
  },
  postureTopTitle: {
    color: colors.onSurface,
    fontFamily: 'SourceSerif4_400Regular',
    fontSize: 24,
    lineHeight: 32,
  },
  postureScroll: {
    gap: 16,
    paddingHorizontal: 24,
    paddingTop: 126,
  },
  postureOption: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.56)',
    borderColor: 'rgba(187,202,194,0.46)',
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: 'row',
    height: 96,
    paddingHorizontal: 20,
  },
  postureOptionActive: {
    backgroundColor: 'rgba(242,237,231,0.72)',
    borderColor: colors.timerPrimary,
    boxShadow: '0 10px 30px rgba(0,108,82,0.08)',
  },
  postureIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,108,82,0.06)',
    borderRadius: 26,
    height: 52,
    justifyContent: 'center',
    width: 52,
  },
  postureOptionText: {
    flex: 1,
    marginLeft: 18,
    paddingRight: 12,
  },
  postureName: {
    color: colors.onSurface,
    fontFamily: 'Manrope_800ExtraBold',
    fontSize: 18,
    lineHeight: 24,
    marginBottom: 2,
  },
  postureDesc: {
    color: colors.variant,
    fontFamily: 'SourceSerif4_400Regular',
    fontSize: 13,
    lineHeight: 19,
  },
  ctaPlay: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 34,
    height: 68,
    justifyContent: 'center',
    marginBottom: 12,
    width: 68,
    boxShadow: '0 8px 20px rgba(51,79,43,0.24)',
  },
  ctaTitle: {
    color: colors.primary,
    fontFamily: 'SourceSerif4_700Bold',
    fontSize: 25,
    lineHeight: 32,
  },
  ctaSub: {
    color: colors.outline,
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 11,
    letterSpacing: 1,
    lineHeight: 16,
    marginTop: 4,
  },
  bento: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 64,
    marginTop: 30,
  },
  glassCard: {
    backgroundColor: 'rgba(253,249,242,0.74)',
    borderColor: 'rgba(255,255,255,0.54)',
    borderRadius: 24,
    borderWidth: 1,
    boxShadow: '0 10px 30px rgba(51,79,43,0.035)',
  },
  statCard: {
    backgroundColor: 'rgba(253,249,242,0.76)',
    flex: 1,
    height: 144,
    justifyContent: 'space-between',
    padding: 24,
  },
  statValue: {
    color: colors.onSurface,
    fontFamily: 'SourceSerif4_400Regular',
    fontSize: 28,
    lineHeight: 36,
    marginTop: 4,
  },
  statUnit: {
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 14,
  },
  previewCard: {
    backgroundColor: 'rgba(253,249,242,0.78)',
    overflow: 'hidden',
    padding: 24,
  },
  previewTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
  },
  previewTitle: {
    color: colors.variant,
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 12,
    letterSpacing: 1.4,
    textTransform: 'uppercase',
  },
  previewText: {
    color: colors.variant,
    fontFamily: 'Manrope_400Regular',
    fontSize: 16,
    lineHeight: 26,
  },
  calendarScroll: {
    paddingHorizontal: 20,
    paddingTop: 104,
  },
  calendarHeader: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    flexDirection: 'row',
    justifyContent: 'space-between',
    left: 0,
    paddingBottom: 16,
    paddingHorizontal: 22,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 10,
  },
  calendarHeaderTitle: {
    color: colors.primary,
    fontFamily: 'SourceSerif4_400Regular',
    fontSize: 28,
    lineHeight: 36,
  },
  figmaCalendarScroll: {
    paddingHorizontal: 20,
    paddingTop: 112,
  },
  growthCard: {
    alignItems: 'center',
    borderRadius: 22,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 18,
    minHeight: 96,
    paddingHorizontal: 22,
    paddingVertical: 18,
  },
  growthLabel: {
    color: colors.variant,
    fontFamily: 'Manrope_400Regular',
    fontSize: 14,
    lineHeight: 20,
  },
  growthText: {
    color: colors.primary,
    fontFamily: 'SourceSerif4_400Regular',
    fontSize: 22,
    lineHeight: 30,
    marginTop: 6,
  },
  growthIconCircle: {
    alignItems: 'center',
    backgroundColor: 'rgba(202,236,188,0.35)',
    borderRadius: 38,
    height: 76,
    justifyContent: 'center',
    width: 76,
  },
  monthStatsRow: {
    flexDirection: 'row',
    gap: 14,
    marginBottom: 18,
  },
  monthStatCard: {
    flex: 1,
    minHeight: 92,
    paddingHorizontal: 20,
    paddingVertical: 18,
  },
  monthStatLabel: {
    color: colors.variant,
    fontFamily: 'Manrope_400Regular',
    fontSize: 14,
    lineHeight: 20,
  },
  monthStatValue: {
    color: colors.primary,
    fontFamily: 'SourceSerif4_400Regular',
    fontSize: 20,
    lineHeight: 28,
    marginTop: 14,
  },
  streakCard: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 34,
    minHeight: 90,
    paddingHorizontal: 20,
    paddingVertical: 18,
  },
  streakDots: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  streakDot: {
    backgroundColor: colors.primary,
    borderColor: colors.surface,
    borderRadius: 18,
    borderWidth: 2,
    height: 36,
    marginLeft: -8,
    width: 36,
  },
  streakDotLight: {
    backgroundColor: colors.primarySoft,
  },
  streakDotDark: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderColor: colors.surface,
    borderRadius: 18,
    borderWidth: 2,
    height: 36,
    justifyContent: 'center',
    marginLeft: -8,
    width: 36,
  },
  streakDotText: {
    color: colors.white,
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  monthCalendarCard: {
    borderRadius: 22,
    marginBottom: 30,
    overflow: 'hidden',
    paddingHorizontal: 20,
    paddingTop: 28,
    paddingBottom: 22,
  },
  monthCalendarBg: {
    height: 230,
    left: 66,
    opacity: 0.035,
    position: 'absolute',
    top: 72,
    width: 230,
  },
  monthHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  monthTitle: {
    color: colors.onSurface,
    fontFamily: 'Manrope_800ExtraBold',
    fontSize: 18,
    lineHeight: 24,
  },
  monthArrows: {
    flexDirection: 'row',
    gap: 16,
  },
  monthArrow: {
    color: colors.outline,
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 28,
    lineHeight: 30,
  },
  weekRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  weekLabel: {
    color: colors.outline,
    fontFamily: 'Manrope_400Regular',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    width: 36,
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  dayCell: {
    alignItems: 'center',
    height: 52,
    justifyContent: 'center',
    width: '14.285%',
  },
  dayBubble: {
    alignItems: 'center',
    borderRadius: 12,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  dayBubbleSelected: {
    backgroundColor: colors.primary,
    boxShadow: '0 8px 18px rgba(51,79,43,0.22)',
  },
  dayText: {
    color: colors.onSurface,
    fontFamily: 'Manrope_400Regular',
    fontSize: 18,
    lineHeight: 24,
  },
  dayTextMuted: {
    color: 'rgba(67,72,64,0.18)',
  },
  dayTextSelected: {
    color: colors.white,
    fontFamily: 'Manrope_800ExtraBold',
  },
  recordDot: {
    backgroundColor: 'rgba(67,72,64,0.45)',
    borderRadius: 4,
    height: 6,
    marginTop: 3,
    width: 6,
  },
  recordDotSelected: {
    backgroundColor: colors.white,
  },
  selectedRecordCard: {
    borderRadius: 22,
    overflow: 'hidden',
  },
  selectedDateBar: {
    backgroundColor: 'rgba(236,232,225,0.45)',
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  selectedDateText: {
    color: colors.primary,
    fontFamily: 'Manrope_700Bold',
    fontSize: 15,
    lineHeight: 22,
  },
  selectedRecordBody: {
    padding: 20,
  },
  selectedRecordTop: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 22,
  },
  selectedPosture: {
    color: colors.onSurface,
    fontFamily: 'SourceSerif4_400Regular',
    fontSize: 21,
    lineHeight: 28,
  },
  selectedDurationRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  selectedDuration: {
    color: colors.variant,
    fontFamily: 'Manrope_400Regular',
    fontSize: 17,
    lineHeight: 24,
  },
  selectedPostureIcon: {
    alignItems: 'center',
    backgroundColor: colors.surfaceWhite,
    borderRadius: 12,
    height: 58,
    justifyContent: 'center',
    width: 58,
    boxShadow: '0 8px 20px rgba(51,79,43,0.07)',
  },
  noteBox: {
    backgroundColor: 'rgba(255,254,250,0.5)',
    borderColor: 'rgba(195,200,189,0.42)',
    borderRadius: 18,
    borderWidth: 1,
    padding: 16,
  },
  noteTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    marginBottom: 8,
  },
  noteTitle: {
    color: colors.primary,
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 13,
    lineHeight: 20,
  },
  selectedNote: {
    color: colors.variant,
    fontFamily: 'Manrope_400Regular',
    fontSize: 15,
    lineHeight: 24,
  },
  calendarSummary: {
    marginBottom: 28,
  },
  calendarTitle: {
    color: colors.onSurface,
    fontFamily: 'SourceSerif4_400Regular',
    fontSize: 34,
    lineHeight: 42,
    marginTop: 8,
  },
  calendarSubtitle: {
    color: colors.variant,
    fontFamily: 'Manrope_400Regular',
    fontSize: 14,
    lineHeight: 22,
    marginTop: 6,
  },
  emptyHistoryCard: {
    padding: 24,
  },
  emptyHistoryTitle: {
    color: colors.onSurface,
    fontFamily: 'SourceSerif4_600SemiBold',
    fontSize: 20,
    lineHeight: 28,
  },
  emptyHistoryText: {
    color: colors.variant,
    fontFamily: 'Manrope_400Regular',
    fontSize: 14,
    lineHeight: 22,
    marginTop: 8,
  },
  historyGroup: {
    marginBottom: 28,
  },
  historyDate: {
    color: colors.outline,
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 12,
    letterSpacing: 1.2,
    lineHeight: 16,
    marginBottom: 12,
    textTransform: 'uppercase',
  },
  historyCard: {
    marginBottom: 12,
    padding: 18,
  },
  historyCardTop: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  historyPosture: {
    color: colors.onSurface,
    fontFamily: 'SourceSerif4_600SemiBold',
    fontSize: 20,
    lineHeight: 28,
  },
  historyMeta: {
    color: colors.outline,
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 2,
  },
  historyDuration: {
    alignItems: 'center',
    backgroundColor: 'rgba(202,236,188,0.36)',
    borderRadius: 999,
    flexDirection: 'row',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  historyDurationText: {
    color: colors.primary,
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 12,
    lineHeight: 16,
  },
  historyNote: {
    color: colors.variant,
    fontFamily: 'Manrope_400Regular',
    fontSize: 14,
    lineHeight: 22,
    marginTop: 14,
  },
  historyTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  historyTag: {
    backgroundColor: 'rgba(230,226,220,0.52)',
    borderRadius: 8,
    color: colors.variant,
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    lineHeight: 18,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  readMore: {
    alignSelf: 'flex-end',
    color: colors.primary,
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 12,
    letterSpacing: 1.2,
    marginTop: 16,
  },
  bottomTabs: {
    alignItems: 'center',
    backgroundColor: 'rgba(253,249,242,0.94)',
    borderTopColor: 'rgba(195,200,189,0.22)',
    borderTopWidth: 1,
    bottom: 0,
    flexDirection: 'row',
    height: 74,
    justifyContent: 'space-around',
    left: 0,
    paddingHorizontal: 16,
    position: 'absolute',
    right: 0,
  },
  tab: {
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  tabLabel: {
    color: 'rgba(67,72,64,0.5)',
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 10,
    lineHeight: 14,
  },
  tabActive: {
    color: colors.primary,
    fontFamily: 'Manrope_800ExtraBold',
  },
  timerScreen: {
    flex: 1,
  },
  timerContent: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 120,
  },
  poseInfo: {
    alignItems: 'center',
    gap: 8,
  },
  timerPose: {
    color: colors.timerPrimary,
    fontFamily: 'SourceSerif4_400Regular',
    fontSize: 28,
    lineHeight: 36,
    textAlign: 'center',
  },
  timerCenter: {
    alignItems: 'center',
    height: 340,
    justifyContent: 'center',
    width: 340,
  },
  timerSvg: {
    position: 'absolute',
  },
  timerReadout: {
    alignItems: 'center',
  },
  timerDigits: {
    color: colors.timerPrimary,
    fontFamily: 'SourceSerif4_300Light',
    fontSize: 48,
    lineHeight: 56,
    textAlign: 'center',
  },
  timerPrompt: {
    color: 'rgba(60,74,67,0.78)',
    fontFamily: 'SourceSerif4_400Regular_Italic',
    fontSize: 20,
    lineHeight: 32,
    marginTop: 16,
    textAlign: 'center',
  },
  controlPanel: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 34,
    justifyContent: 'center',
  },
  sideControl: {
    alignItems: 'center',
    gap: 8,
    width: 64,
  },
  sideControlIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.42)',
    borderRadius: 28,
    height: 56,
    justifyContent: 'center',
    width: 56,
  },
  controlLabel: {
    color: colors.variant,
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 12,
    letterSpacing: 1.2,
  },
  mainControl: {
    alignItems: 'center',
    backgroundColor: colors.timerPrimary,
    borderRadius: 40,
    height: 80,
    justifyContent: 'center',
    width: 80,
    boxShadow: '0 12px 26px rgba(0,108,82,0.22)',
  },
  exitPractice: {
    color: colors.outline,
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 12,
    letterSpacing: 1.2,
    marginTop: 22,
  },
  recordScroll: {
    paddingHorizontal: 24,
    paddingTop: 104,
  },
  recordSummary: {
    alignItems: 'center',
    marginBottom: 48,
  },
  recordHeroRow: {
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 8,
  },
  recordHeroText: {
    color: colors.primary,
    fontFamily: 'SourceSerif4_300Light',
    fontSize: 34,
    lineHeight: 42,
  },
  inlineMinutes: {
    color: colors.primary,
    fontFamily: 'SourceSerif4_300Light',
    fontSize: 34,
    height: 42,
    includeFontPadding: false,
    lineHeight: 42,
    minWidth: 52,
    paddingHorizontal: 0,
    paddingVertical: 0,
    textAlign: 'center',
    textAlignVertical: 'center',
  },
  recordPosture: {
    color: colors.outline,
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 12,
    letterSpacing: 1.2,
    marginTop: 8,
    textTransform: 'uppercase',
  },
  summaryLine: {
    backgroundColor: colors.outlineSoft,
    height: 1,
    marginTop: 22,
    width: 48,
  },
  formSection: {
    marginBottom: 44,
  },
  sectionLabelRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
  },
  formLabel: {
    color: colors.outline,
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 12,
    letterSpacing: 1.2,
    lineHeight: 16,
  },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  chip: {
    backgroundColor: colors.surfaceWhite,
    borderColor: colors.outlineSoft,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 7,
  },
  chipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  chipText: {
    color: colors.variant,
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
    lineHeight: 20,
  },
  chipTextActive: {
    color: colors.white,
    fontFamily: 'Manrope_400Regular',
  },
  noteInput: {
    backgroundColor: 'rgba(255,254,250,0.55)',
    borderColor: 'rgba(195,200,189,0.45)',
    borderRadius: 24,
    borderWidth: 1,
    color: colors.onSurface,
    fontFamily: 'Manrope_400Regular',
    fontSize: 18,
    lineHeight: 28,
    minHeight: 192,
    padding: 24,
  },
  tagWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  tagChip: {
    backgroundColor: 'rgba(230,226,220,0.52)',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  tagActive: {
    backgroundColor: colors.primary,
  },
  tagText: {
    color: colors.variant,
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
    lineHeight: 20,
  },
  tagTextActive: {
    color: colors.white,
  },
  saveBar: {
    bottom: 0,
    left: 0,
    paddingHorizontal: 24,
    paddingTop: 26,
    position: 'absolute',
    right: 0,
  },
  saveBarActions: {
    alignSelf: 'center',
    flexDirection: 'row',
    gap: 12,
    maxWidth: 600,
    width: '100%',
  },
  deleteButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,254,250,0.72)',
    borderColor: 'rgba(0,108,82,0.22)',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  deleteText: {
    color: colors.primary,
    fontFamily: 'Manrope_700Bold',
    fontSize: 16,
    lineHeight: 28,
  },
  saveButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 16,
    flex: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'center',
    paddingVertical: 18,
    boxShadow: '0 10px 24px rgba(51,79,43,0.18)',
  },
  saveText: {
    color: colors.white,
    fontFamily: 'Manrope_700Bold',
    fontSize: 18,
    lineHeight: 28,
  },
  pressed: {
    opacity: 0.86,
    transform: [{ scale: 0.98 }],
  },
  disabled: {
    opacity: 0.45,
  },
});
